//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отработки
    {
        public int Номер_отработки { get; set; }
        public string Студент__номер_студенческого_билета_ { get; set; }
        public string Предмет { get; set; }
        public Nullable<short> Оценка { get; set; }
        public Nullable<System.DateTime> Дата_отработки { get; set; }
        public string Преподаватель { get; set; }
    
        public virtual Преподаватели Преподаватели { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
