//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Преподаватели
    {
        public Преподаватели()
        {
            this.Отработки = new HashSet<Отработки>();
            this.Предметы = new HashSet<Предметы>();
        }
    
        public string Номер_трудовой_книжки { get; set; }
        public string Фамилия_И_О_ { get; set; }
        public string Кафедра { get; set; }
        public string Кабинет { get; set; }
    
        public virtual ICollection<Отработки> Отработки { get; set; }
        public virtual ICollection<Предметы> Предметы { get; set; }
    }
}
