//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        public Студенты()
        {
            this.Отработки = new HashSet<Отработки>();
        }
    
        public string Номер_студенческого_билета { get; set; }
        public string Фамилия { get; set; }
        public string Факультет { get; set; }
        public string Специальность { get; set; }
        public Nullable<short> Курс { get; set; }
        public Nullable<short> Группа { get; set; }
        public Nullable<short> Подгруппа { get; set; }
    
        public virtual ICollection<Отработки> Отработки { get; set; }
        public virtual Факультеты Факультеты { get; set; }
        public virtual УСПЕВАЕМОСТЬ УСПЕВАЕМОСТЬ { get; set; }
    }
}
